-- Make booking_reference auto-generated by trigger, allow NULL temporarily
ALTER TABLE public.bookings ALTER COLUMN booking_reference DROP NOT NULL;

-- Update existing trigger to ensure it runs before insert
DROP TRIGGER IF EXISTS set_booking_reference_trigger ON public.bookings;

CREATE TRIGGER set_booking_reference_trigger
  BEFORE INSERT ON public.bookings
  FOR EACH ROW
  EXECUTE FUNCTION public.set_booking_reference();